- name: Check UiPath CLI Installation
  'on': null
  workflow_dispatch: >-
    if command -v uipcli > /dev/null; then 
        echo "UiPath CLI is installed."
    uipcli --version else echo "UiPath CLI is NOT installed." exit 1 fi
